In [1]:
import numpy as np

In [2]:
nparray = np.array([2,4,5,6,7,54,657,67])

In [3]:
np.shape(nparray)

(8,)

In [4]:
nparray2 = np.array([[33,4,3,4,5,7,4]])

In [5]:
np.shape(nparray2)

(1, 7)

In [6]:
nparray3 = ([[[3,45,3,4,4,3,5]]])

In [7]:
np.shape(nparray3)

(1, 1, 7)

In [16]:
nparray3 = np.array([[[3,45,3,4,4,3,5]],[[3,45,3,4,4,3,5]]])

In [17]:
np.shape(nparray3)

(2, 1, 7)

In [19]:
nparray2 = np.array([[33,4,3,4,5,7,4],[33,4,3,4,5,7,4]])

In [20]:
np.shape(nparray2)

(2, 7)

In [21]:
np.ndim(nparray2)

2

In [22]:
np.ndim(nparray3)

3

In [23]:
np.ndim(nparray)

1

In [3]:
a1 = np.array([3,4,6,81,32,45])

NameError: name 'np' is not defined

In [2]:
np.size(a1)

NameError: name 'np' is not defined

In [4]:
import numpy as np

In [5]:
a1 = np.array([3,4,6,81,32,45])

In [6]:
np.size(a1)

6

In [8]:
a1 = np.array([[3,4,6,81,32,45],[3,4,6,81,32,45]])

In [9]:
np.size(a1)|

SyntaxError: invalid syntax (3322586918.py, line 1)

In [10]:
a1.dtype

dtype('int32')

In [11]:
a1 = np.array([[3,4,6,81,32.6,45],[3,4,6,81,32,45]])

In [12]:
a1.dtype

dtype('float64')

In [15]:
starr =np.array(['hdgsd','hghsd','hjdjk'])

In [16]:
starr.dtype

dtype('<U5')

In [17]:
np.zeros((2,2)) #to know about the matrix form use for know as row and column

array([[0., 0.],
       [0., 0.]])

In [18]:
np.zeros((3,2)) 

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

AttributeError: module 'numpy' has no attribute 'one'

In [21]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [22]:
np.full((3,3),3)

array([[3, 3, 3],
       [3, 3, 3],
       [3, 3, 3]])

In [24]:
np.random.rand(2,2)

array([[0.49431359, 0.64725592],
       [0.53788271, 0.27377331]])

In [25]:
np.random.rand(3,3)

array([[0.94508403, 0.55668731, 0.33193647],
       [0.1085584 , 0.75017509, 0.22762767],
       [0.05365232, 0.14564288, 0.38037626]])

In [26]:
a1 = np.array([3,4,6,81,32.6,45])

In [27]:
a1.mean() #to find average

28.599999999999998

In [28]:
a1.min() #to find the minimum value

3.0

In [29]:
a1.max() 

81.0

In [30]:
a1.std() #to find the variants means kon si value kitne rate me varient kar rhi hai std= standard deviation

28.290163190291665

In [31]:
a1.var() #var means variance means square of standard daviation

800.3333333333335

In [32]:
m1 = np.array([[2,3],[23,2]])

In [33]:
m2 = np.array([[2,3],[23,2]])

In [34]:
m1@m2 #to multiply two metrix use @ but multiply of two value use is * 

array([[73, 12],
       [92, 73]])

In [35]:
m1*m2

array([[  4,   9],
       [529,   4]])

In [40]:
d1= np.array([2,3,45,79,7,21,23])

In [42]:
d1.reshape([2,3,45,79,7,21,23])

ValueError: cannot reshape array of size 7 into shape (2,3,45,79,7,21,23)

In [44]:
d1.reshape(1,7) #reshape is use for covert data one dimensional into two dimensional

array([[ 2,  3, 45, 79,  7, 21, 23]])

In [45]:
d1= np.array([2,3,45,79,7,21])

In [46]:
d1.reshape(1,6)

array([[ 2,  3, 45, 79,  7, 21]])

In [47]:
d1.reshape(2,3)

array([[ 2,  3, 45],
       [79,  7, 21]])

In [48]:
d1.reshape(3,2)

array([[ 2,  3],
       [45, 79],
       [ 7, 21]])

In [49]:
x = d1.reshape(3,2)

In [50]:
x

array([[ 2,  3],
       [45, 79],
       [ 7, 21]])

In [51]:
x.flatten() #flatten is used for again shape form me convert karne ke liye

array([ 2,  3, 45, 79,  7, 21])

In [52]:
y =x.flatten()

In [53]:
y

array([ 2,  3, 45, 79,  7, 21])

In [55]:
y[0] #[]used for specific range or find the index value

2

In [56]:
y[3]

79

In [57]:
y[0:3]

array([ 2,  3, 45])

In [59]:
y[::-1] # used for reverse the array 

array([21,  7, 79, 45,  3,  2])